Parametrized tests
Kosmoastronauta/Parking pull request #1
Opened 2019-07-18 13:13 UTC by Kosmoastronauta

2019-07-19 07:42 UTC, bkita requested changes

2019-07-19 07:42 UTC, bkita commented on src/main/java/Traffic/Reservation.java
>      public boolean isFree(int number_of_space)
Is it for parking space or entire parking? Can You please rename method to more descriptive?

2019-07-19 07:42 UTC, bkita commented on src/main/java/Traffic/Reservation.java
>      public void reset()
same as above

2019-07-19 07:42 UTC, bkita commented on src/main/java/Traffic/Reservation.java
> +
delete empty line

2019-07-19 07:42 UTC, bkita commented on src/main/java/Traffic/Reservation.java
>      protected boolean possibleToReserve(Time oldTime, Time newTime)
if method returns boolean, it should start from is -> isPossibleToReserve

2019-07-19 07:42 UTC, bkita commented on src/main/java/Traffic/Reservation.java
>      protected boolean possibleToReserve(Time oldTime, Time newTime)
maybe isParkingPlacePossibleToReserve

2019-07-19 07:42 UTC, bkita commented on src/main/java/Traffic/Time.java
> +    protected boolean validation(int hourFrom, int minFrom, int hourTo, int minTo)
validation of what?

2019-07-19 07:42 UTC, bkita commented on src/main/java/Traffic/Time.java
> +
you dont need that many empty spaces

2019-07-19 07:42 UTC, bkita commented on src/test/java/Traffic/ParametrizedRezerwationTest.java
> +    public ParametrizedRezerwationTest(int hourFrom, int minFrom, int hourTo, int minTo)
Reservation ?

2019-07-19 07:42 UTC, bkita commented on src/test/java/Traffic/ParametrizedRezerwationTest.java
> +    public void resetTest()
test name should be more descriptive

2019-07-19 07:42 UTC, bkita commented on src/test/java/Traffic/ReservationAvaliableParametrizedTest.java
> +
delete empty line

2019-07-19 07:42 UTC, bkita commented on src/test/java/Traffic/ReservationAvaliableParametrizedTest.java
> +
empty lines?

2019-07-19 07:42 UTC, bkita commented on src/test/java/Traffic/ReservationAvaliableParametrizedTest.java
> +
empty lines

2019-07-19 07:42 UTC, bkita commented on src/test/java/Traffic/ReservationAvaliableParametrizedTest.java
> +
empty lines

2019-07-19 07:42 UTC, bkita commented on src/test/java/Traffic/ReservationTest.java
> +
empty lines

2019-07-19 07:42 UTC, bkita commented on src/test/java/Traffic/TimeTest.java
> +
empty lines

2019-07-19 09:29 UTC, merged

2019-07-23 08:27 UTC, salci1990 commented
https://github.com/salci1990/RESTassuredTests

2019-07-23 10:42 UTC, salci1990 commented
strefakursow.pl
bartosz.kita@gmail.com
0MyPython0123!@#